### PR TITLE
Add common config from es6 toolkit

### PR DESCRIPTION
**Pull request by adam-h**
Example usage in toolkit PR: https://github.com/polleverywhere/toolkit/pull/235

This PR refactors this repo for our new "es6" projects to share the config for:
 - Babel
 - eslint
 - sass-lint

This is using their standard ways. Babel and eslint use npm config packages referenced as a base config. sass-lint just points to a file, but this can be published on npm too for consistency.

_Note that the babel-preset-pe package is already published and in use, just doesn't have a github home yet_

### CODE REVIEW

**Comment by adam-h** [comment]
@steel @nguyenj What are your thoughts on this approach to the config?

I don't want to get into the weeds about exactly what the common rules are - this is just for how to actually share it. As toolkit is the only repo using the new style, I am just using that config as-is. We can work on moving to different rule sets in future versions.

**Comment by nguyenj** [comment]
We can remove `eslint` since we should be moving towards [JavaScript Standard Style](https://standardjs.com), you've already made this argument and I agree–so there's no need to deviate. 

As for the `babel` configuration, not all apps support the same set of browsers. And there's no need to penalize apps that don't support the older browser where other apps might still need to–I know we can import and change the object; so maybe we should have the default configuration with the lowest denominator? [web presenter needs safari 6](https://github.com/polleverywhere/web_presenter/blob/66628bb2675524f73aa5ba76d931f9a6b9fb1ce9/Gruntfile.coffee#L160) and [viz needed safari 6](https://github.com/polleverywhere/viz/blob/dfcebfc28fbff01b7d3918b2644bc7e3574c880a/Gruntfile.coffee#L229)!! I think viz might be breaking again @steel the new presets that viz is using is supported >= 8.

**Comment by adam-h** [comment]
@nguyenj The question is, how soon are we moving? Toolkit at least isn't there yet, so we may want this config for now and then move further later?

As for the babel config, I'm happy to change to Safari 6 if that's what's needed by some apps as a minimum. Although...why are we still supporting that?

**Comment by adam-h** [comment]
@nguyenj Made some tweaks. Happy to merge? For now I just want these in the repo proper as they are being used by projects

Want to get this into a common place and we can iterate on the actual rules once it's in.

**Comment by adam-h** [comment]
@nguyenj Merging this so it has a home, as I noticed you fixed the bug in the prior version by releasing the script-land PR code. It's home is here now, going to close out that other PR.

We can iterate on the rules in further PR dicsussions.

**Pull request merged**
